import os

file_path = r"c:\Users\Aquib Belal\Documents\Chemistry Companion\api\routes\llm_explanation.py"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# Add imports for the new service
imports_addition = """from services.ai.docking_expert import DockingExpertService
expert_service = DockingExpertService()

def _format_htmx_response(response, status_color="indigo"):
    status_text = f"Generated by {response.provider_used}"
    if getattr(response, 'is_fallback', False):
        status_color = "amber"
        status_text = f"Generated by fallback ({response.provider_used})"
        
    error_html = ""
    if getattr(response, 'error', None):
        error_html = f'<div class="mb-4 text-xs bg-red-50 text-red-600 border border-red-200 rounded p-2">Warning: {response.error}</div>'

    html = f'''
    <div class="relative">
        {error_html}
        <div class="absolute top-0 right-0 text-[10px] uppercase font-bold tracking-wider px-2 py-1 rounded bg-{status_color}-100 text-{status_color}-700 dark:bg-{status_color}-900/30 dark:text-{status_color}-400">
            {status_text}
        </div>
        <div class="prose prose-sm prose-{status_color} dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 whitespace-pre-wrap mt-6">{response.text}</div>
    </div>
    '''
    return HTMLResponse(html)
"""

if "DockingExpertService" not in content:
    content = content.replace("import json\n", "import json\n" + imports_addition + "\n")

# New HTMX Endpoints
new_endpoints = """
@router.post("/expert/pose", response_class=HTMLResponse)
async def expert_pose(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if not poses:
            return HTMLResponse("<div class='text-slate-500'>No pose selected.</div>")
        
        pose = poses[0]
        interactions = interactions_dict.get(str(pose.get('rank', 1)), [])
        
        response = expert_service.explain_pose(smiles, pose, interactions)
        return _format_htmx_response(response, "indigo")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/compare", response_class=HTMLResponse)
async def expert_compare(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if len(poses) < 2:
            return HTMLResponse("<div class='text-slate-500'>Select at least two poses to compare.</div>")
        
        # Ensure keys are ints for the expert service if needed, or just pass dict
        response = expert_service.compare_poses(smiles, poses, interactions_dict)
        return _format_htmx_response(response, "blue")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/improve", response_class=HTMLResponse)
async def expert_improve(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if not poses:
            return HTMLResponse("<div class='text-slate-500'>No pose selected for improvement analysis.</div>")
            
        pose = poses[0]
        interactions = interactions_dict.get(str(pose.get('rank', 1)), [])
        
        response = expert_service.suggest_improvements(smiles, pose, interactions)
        return _format_htmx_response(response, "emerald")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/report", response_class=HTMLResponse)
async def expert_report(request: Request, poses_json: str = Form("[]"), interactions_json: str = Form("{}"), metadata_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        metadata = json.loads(metadata_json)
        
        response = expert_service.generate_report(metadata, poses, interactions_dict)
        return _format_htmx_response(response, "purple")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")
"""

if "@router.post(\"/expert/pose\"" not in content:
    content += new_endpoints

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)
