"""
chemistry_companion/core/conversion_utils.py
=============================================
Format-conversion utilities: SMILES/InChI/Mol block/XYZ + 3D embedding.

Scientific note:
ETKDGv3 = fast heuristic conformer (CSD torsion knowledge).
NOT quantum-optimised. Use ORCA/Gaussian (Phase 4) for spectra or energies.
"""
import logging
from typing import Optional

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem.inchi import MolToInchi, InchiToInchiKey, MolFromInchi

logger = logging.getLogger(__name__)


def smiles_to_canonical(smiles: str) -> str:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None: raise ValueError(f"Invalid SMILES: {smiles!r}")
    return Chem.MolToSmiles(mol, isomericSmiles=True)

def smiles_to_inchi(smiles: str) -> str:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None: raise ValueError(f"Invalid SMILES: {smiles!r}")
    inchi = MolToInchi(mol)
    if not inchi: raise RuntimeError(f"InChI generation failed for: {smiles!r}")
    return inchi

def smiles_to_inchikey(smiles: str) -> str:
    return InchiToInchiKey(smiles_to_inchi(smiles))

def smiles_to_molblock(smiles: str) -> str:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None: raise ValueError(f"Invalid SMILES: {smiles!r}")
    AllChem.Compute2DCoords(mol)
    return Chem.MolToMolBlock(mol)

def inchi_to_smiles(inchi: str) -> str:
    mol = MolFromInchi(inchi)
    if mol is None: raise ValueError(f"Could not parse InChI: {inchi!r}")
    return Chem.MolToSmiles(mol, isomericSmiles=True)

def inchi_to_molblock(inchi: str) -> str:
    mol = MolFromInchi(inchi)
    if mol is None: raise ValueError(f"Could not parse InChI: {inchi!r}")
    AllChem.Compute2DCoords(mol)
    return Chem.MolToMolBlock(mol)

def mol_to_smiles(mol: Chem.Mol, isomeric: bool = True) -> str:
    return Chem.MolToSmiles(mol, isomericSmiles=isomeric)

def mol_to_inchi(mol: Chem.Mol) -> str:
    inchi = MolToInchi(mol)
    if not inchi: raise RuntimeError("InChI generation failed.")
    return inchi

def mol_to_inchikey(mol: Chem.Mol) -> str:
    return InchiToInchiKey(mol_to_inchi(mol))

def mol_to_molblock(mol: Chem.Mol, compute_2d: bool = True) -> str:
    if compute_2d: AllChem.Compute2DCoords(mol)
    return Chem.MolToMolBlock(mol)


def embed_3d(mol: Chem.Mol, optimize: bool = True, random_seed: int = 42) -> Chem.Mol:
    """
    Add 3D coordinates via ETKDGv3 + optional MMFF94 minimisation.

    MMFF94 fallback tiers:
        0  = converged (success)
        1  = not fully converged (logged warning, coordinates still usable)
       -1  = parameters unavailable (logged warning, uses raw ETKDG coords)
        Exception = unexpected failure (logged warning, uses raw ETKDG coords)
    """
    mol_h  = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = random_seed
    result = AllChem.EmbedMolecule(mol_h, params)

    if result != 0:
        raise RuntimeError(
            "ETKDGv3 3D embedding failed. "
            "Check molecule validity (sanitisation, unusual valence)."
        )

    if optimize:
        try:
            ff_result = AllChem.MMFFOptimizeMolecule(mol_h, mmffVariant="MMFF94")
            if ff_result == 1:
                logger.warning("MMFF94 did not fully converge. Coordinates usable.")
            elif ff_result == -1:
                logger.warning("MMFF94 parameters unavailable. Using raw ETKDGv3.")
        except Exception as exc:
            logger.warning("MMFF94 failed (%s). Using raw ETKDGv3.", exc)

    logger.info("3D embedding complete (seed=%d, optimised=%s)", random_seed, optimize)
    return mol_h


def mol_to_xyz(mol: Chem.Mol) -> str:
    """Export 3D molecule to XYZ format string. Requires prior embed_3d()."""
    if mol.GetNumConformers() == 0:
        raise ValueError("No 3D conformer. Run conversion_utils.embed_3d() first.")
    conf  = mol.GetConformer()
    n     = mol.GetNumAtoms()
    lines = [str(n), "Generated by Chemistry Companion (ETKDGv3/MMFF94)"]
    for i, atom in enumerate(mol.GetAtoms()):
        pos = conf.GetAtomPosition(i)
        lines.append(f"{atom.GetSymbol():2s}  {pos.x:10.5f}  {pos.y:10.5f}  {pos.z:10.5f}")
    return "\n".join(lines)


def batch_smiles_to_inchi(smiles_list: list[str]) -> list[dict]:
    results = []
    for smi in smiles_list:
        try:
            inchi = smiles_to_inchi(smi)
            ikey  = InchiToInchiKey(inchi)
            results.append({"smiles": smi, "inchi": inchi, "inchikey": ikey, "error": None})
        except Exception as exc:
            logger.error("Conversion failed for %r: %s", smi, exc)
            results.append({"smiles": smi, "inchi": None, "inchikey": None, "error": str(exc)})
    return results


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    smi = "CC(=O)Oc1ccccc1C(=O)O"
    print("Canonical:", smiles_to_canonical(smi))
    print("InChIKey :", smiles_to_inchikey(smi))
    mol3d = embed_3d(Chem.MolFromSmiles(smi))
    print("XYZ first atom:", mol_to_xyz(mol3d).splitlines()[2])