from fastapi import APIRouter, HTTPException, Request, Form
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import List, Dict, Any

from llm.explanation_models import DockingExplanationRequest, PoseExplanationRequest, DockingExplanationResponse
from core.llm_utils import (
    explain_docking,
    get_available_providers,
    get_active_provider,
    set_primary_provider,
    reset_primary_provider
)

router = APIRouter()

class ProviderUpdateRequest(BaseModel):
    provider: str

@router.get("/providers")
async def list_providers():
    """Return a list of all available LLM providers for the GUI."""
    return get_available_providers()

@router.get("/provider")
async def active_provider():
    """Return the currently active primary provider."""
    return {"active": get_active_provider()}

@router.post("/provider")
async def switch_provider(req: ProviderUpdateRequest):
    """Switch the primary LLM provider at runtime."""
    if req.provider.lower() == "auto":
        reset_primary_provider()
        return {"status": "success", "active": get_active_provider()}
    
    try:
        set_primary_provider(req.provider)
        return {"status": "success", "active": get_active_provider()}
    except ValueError as e:
        raise HTTPException(400, str(e))

@router.post("/explain_docking", response_model=DockingExplanationResponse)
async def api_explain_docking(req: DockingExplanationRequest):
    try:
        # Use the new multi-provider explanation engine
        explanation = explain_docking(
            smiles=req.smiles,
            poses=req.poses,
            interactions=req.interactions
        )
        return DockingExplanationResponse(explanation=explanation.text)
    except Exception as e:
        raise HTTPException(500, f"Explanation failed: {str(e)}")

@router.post("/explain_pose", response_model=DockingExplanationResponse)
async def api_explain_pose(req: PoseExplanationRequest):
    try:
        explanation = explain_docking(
            smiles=req.smiles,
            poses=[req.pose],
            interactions=req.interactions
        )
        return DockingExplanationResponse(explanation=explanation.text)
    except Exception as e:
        raise HTTPException(500, f"Explanation failed: {str(e)}")

import json
from functools import lru_cache
from services.ai.docking_expert import DockingExpertService


@lru_cache(maxsize=1)
def get_expert_service() -> DockingExpertService:
    return DockingExpertService()

def _format_htmx_response(response, status_color="indigo"):
    status_text = f"Generated by {response.provider_used}"
    if getattr(response, 'is_fallback', False):
        status_color = "amber"
        status_text = f"Generated by fallback ({response.provider_used})"
        
    error_html = ""
    if getattr(response, 'error', None):
        error_html = f'<div class="mb-4 text-xs bg-red-50 text-red-600 border border-red-200 rounded p-2">Warning: {response.error}</div>'

    html = f'''
    <div class="relative">
        {error_html}
        <div class="absolute top-0 right-0 text-[10px] uppercase font-bold tracking-wider px-2 py-1 rounded bg-{status_color}-100 text-{status_color}-700 dark:bg-{status_color}-900/30 dark:text-{status_color}-400">
            {status_text}
        </div>
        <div class="prose prose-sm prose-{status_color} dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 whitespace-pre-wrap mt-6">{response.text}</div>
    </div>
    '''
    return HTMLResponse(html)


@router.post("/explain_pose_htmx", response_class=HTMLResponse)
async def explain_pose_htmx(
    request: Request,
    smiles: str = Form(""),
    poses_json: str = Form("[]"),
    interactions_json: str = Form("[]")
):
    try:
        try:
            poses = json.loads(poses_json)
        except Exception:
            poses = []
            
        try:
            interactions = json.loads(interactions_json)
        except Exception:
            interactions = []
        
        explanation = explain_docking(
            smiles=smiles,
            poses=poses,
            interactions=interactions
        )
        
        # Determine styling based on source/fallback
        status_color = "indigo"
        status_text = f"Generated by {explanation.provider_used}"
        if explanation.is_fallback:
            if explanation.source == "template":
                status_color = "amber"
                status_text = "Generated by fallback template"
            else:
                status_color = "blue"
                status_text = f"Generated by fallback provider ({explanation.provider_used})"
                
        # Error badge if there was one
        error_html = ""
        if explanation.error:
            error_html = f'<div class="mb-4 text-xs bg-red-50 text-red-600 border border-red-200 rounded p-2">Warning: Primary LLM failed - {explanation.error}</div>'

        html = f"""
        <div class="relative">
            {error_html}
            <div class="absolute top-0 right-0 text-[10px] uppercase font-bold tracking-wider px-2 py-1 rounded bg-{status_color}-100 text-{status_color}-700 dark:bg-{status_color}-900/30 dark:text-{status_color}-400">
                {status_text}
            </div>
            <div class="prose prose-sm prose-{status_color} dark:prose-invert max-w-none text-slate-700 dark:text-slate-300 whitespace-pre-wrap mt-6">{explanation.text}</div>
        </div>
        """
        return HTMLResponse(html)
    except Exception as e:
        return HTMLResponse(
            f'<div class="p-4 bg-red-50 text-red-600 rounded border border-red-200">Error generating explanation: {str(e)}</div>'
        )

@router.post("/expert/pose", response_class=HTMLResponse)
async def expert_pose(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if not poses:
            return HTMLResponse("<div class='text-slate-500'>No pose selected.</div>")
        
        pose = poses[0]
        interactions = interactions_dict.get(str(pose.get('rank', 1)), [])

        response = get_expert_service().explain_pose(smiles, pose, interactions)
        return _format_htmx_response(response, "indigo")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/compare", response_class=HTMLResponse)
async def expert_compare(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if len(poses) < 2:
            return HTMLResponse("<div class='text-slate-500'>Select at least two poses to compare.</div>")
        
        # Ensure keys are ints for the expert service if needed, or just pass dict
        response = get_expert_service().compare_poses(smiles, poses, interactions_dict)
        return _format_htmx_response(response, "blue")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/improve", response_class=HTMLResponse)
async def expert_improve(request: Request, smiles: str = Form(""), poses_json: str = Form("[]"), interactions_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        if not poses:
            return HTMLResponse("<div class='text-slate-500'>No pose selected for improvement analysis.</div>")
            
        pose = poses[0]
        interactions = interactions_dict.get(str(pose.get('rank', 1)), [])

        response = get_expert_service().suggest_improvements(smiles, pose, interactions)
        return _format_htmx_response(response, "emerald")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")

@router.post("/expert/report", response_class=HTMLResponse)
async def expert_report(request: Request, poses_json: str = Form("[]"), interactions_json: str = Form("{}"), metadata_json: str = Form("{}")):
    try:
        poses = json.loads(poses_json)
        interactions_dict = json.loads(interactions_json)
        metadata = json.loads(metadata_json)
        
        response = get_expert_service().generate_report(metadata, poses, interactions_dict)
        return _format_htmx_response(response, "purple")
    except Exception as e:
        return HTMLResponse(f"<div class='text-red-500'>Error: {str(e)}</div>")
